# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_auto_20170526_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='language',
        ),
        migrations.RemoveField(
            model_name='post',
            name='style',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='no Author', max_length=150),
        ),
    ]
